## W4: Intro to Software for Data Visualizations and Data Cleaning

#### Application: Consumer Expenditure Surveys - Foos consumption

#### Datasource: https://www.bls.gov/cex/tables.htm#topline

#### This notebook presents the basics of how to load, subset, and start creating visualizations. This is the fist applied notebook for Storytelling with Visualizations

In [5]:
#load packages
import pandas as pd
import io

**Reasoning**:
Provide instructions and code for the user to upload their four Excel files from their local machine to the Colab environment.

In [6]:
#load the pre processed data:
url = "https://github.com/juancsherrera/Storytelling/raw/refs/heads/main/data/cu-all-multi-year.xlsx"
df = pd.read_excel(url, header=2)

# Drop rows with all null values
df.dropna(how='all', inplace=True)

display(df)

,Item,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Number of consumer units (in thousands),118843,120171,120770.0,120847.0,121107.0,122287,124416,125670,127006,128437,129549,130001,131439,132242,131234,133595,134090,134556
2,Consumer unit characteristics:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Income before taxes a/,60533,63091,63563.0,62857.0,62481.0,63685,65596,63784,66877,69627,74664,73573,78635,82852,84352,87432,94003,101805
5,Income after taxes a/,58101,60858,61774.0,60753.0,60712.0,61673,63370,56352,58364,60448,64175,63606,67241,71487,74949,78743,83195,87869
7,Age of reference person,48.7,48.8,49.1,49.4,49.4,49.7,50,50.1,50.3,50.5,50.9,50.9,51.1,51.6,52.2,51.8,52.1,52.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225,c Data are likely to have large sampling errors.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
226,"d Prior to 2000, gifts of Alcoholic beverages,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
227,n.a. Not applicable.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
229,"Note: All values have been rounded, and as a r...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
233,"Source: Consumer Expenditure Survey, U.S. Bure...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
#See the data (this works on Google Colab)
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1mExg8mBcGvRwTEnpNTVdGH6MNSQHzeN2C4w6EON_tDQ/edit#gid=0

In [8]:
# Let's subset to look at some of the interesting rows:
items_to_keep = [
    'Average annual expenditures', 'Food', 'Food at home', 'Cereals and bakery products',
    'Cereals and cereal products', 'Bakery products', 'Meats, poultry, fish, and eggs',
    'Beef', 'Pork', 'Other meats', 'Poultry', 'Fish and seafood', 'Eggs',
    'Dairy products', 'Fresh milk and cream', 'Other dairy products',
    'Fruits and vegetables', 'Fresh fruits', 'Fresh vegetables', 'Processed fruits',
    'Processed vegetables', 'Processed fruits and vegetables', 'Other food at home',
    'Sugar and other sweets', 'Fats and oils', 'Miscellaneous foods',
    'Nonalcoholic beverages', 'Food prepared by consumer unit on out-of-town trips',
    'Food away from home', 'Alcoholic beverages', 'Housing', 'Shelter',
    'Owned dwellings', 'Mortgage interest and charges', 'Property taxes',
    'Maintenance, repairs, insurance, other expenses', 'Rented dwellings',
    'Other lodging', 'Utilities, fuels, and public services', 'Natural gas',
    'Electricity', 'Fuel oil and other fuels', 'Telephone services',
    'Residential phone service, VOIP, and phone cards', 'Cellular phone service',
    'Water and other public services', 'Household operations', 'Personal services',
    'Other household expenses', 'Housekeeping supplies', 'Laundry and cleaning supplies',
    'Laundry and cleaning products (new UCC Q20231)', 'Other household products',
    'Postage and stationery', 'Household furnishings and equipment',
    'Household textiles', 'Furniture', 'Floor coverings', 'Major appliances',
    'Small appliances, miscellaneous housewares', 'Miscellaneous household equipment',
    'Apparel and services', 'Men and boys', 'Men, 16 and over', 'Boys, 2 to 15',
    'Women and girls', 'Women, 16 and over', 'Girls, 2 to 15', 'Children under 2',
    'Footwear', 'Other apparel products and services', 'Transportation',
    'Vehicle purchases (net outlay)', 'Cars and trucks, new', 'Cars and trucks, used',
    'Other vehicles', 'Gasoline and motor oil', 'Other vehicle expenses',
    'Vehicle finance charges', 'Maintenance and repairs', 'Vehicle insurance',
    'Vehicle rental, leases, licenses, and other charges', 'Public and other transportation',
    'Health care', 'Health insurance', 'Medical services', 'Drugs', 'Medical supplies',
    'Entertainment', 'Fees and admissions', 'Audio and visual equipm'
]

#let's create a new dataframe that contains only the rows of interest and let's see it
df_filtered = df[df['Item'].isin(items_to_keep)].reset_index(drop=True)

display(df_filtered)

,Item,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Average annual expenditures,48400,49638,50486.0,49067.0,48109.0,49705,51442,51100,53495,55978,57311,60060,61224,63036,61334,66928,72967,77280
1,Food,6111,6133,6443.0,6372.0,6129.0,6458,6599,6602,6759,7023,7203,7729,7923,8169,7316,8289,9343,9985
2,Food at home,3417,3465,3744.0,3753.0,3624.0,3838,3921,3977,3971,4015,4049,4363,4464,4643,4942,5259,5703,6053
3,Cereals and bakery products,446,460,507.0,506.0,502.0,531,538,544,519,518,524,564,569,583,640,672,712,830
4,Cereals and cereal products,143,143,170.0,173.0,165.0,175,182,185,176,172,172,176,178,184,212,210,215,256
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,Children under 2,52,45,50.0,48.0,47.0,22,20,30,31,40,27,32,28,37,c/,NaN,NaN,NaN
98,Other apparel products and services,52,52,47.0,49.0,42.0,52,56,42,52,90,50,43,52,64,c/,NaN,NaN,NaN
99,Transportation,70,109,99.0,86.0,85.0,90,111,100,108,139,101,141,125,133,c/,NaN,NaN,NaN
100,Health care,41,23,22.0,28.0,21.0,30,53,35,35,34,28,21,21,38,c/,NaN,NaN,NaN
101,Entertainment,76,103,89.0,91.0,95.0,93,82,89,89,95,95,98,105,100,c/,NaN,NaN,NaN

In [ ]:
import altair as alt
import pandas as pd

# Extract rows for 'Food' and 'Average annual expenditures'
food_expenditure = df_filtered[df_filtered['Item'] == 'Food'].iloc[0, 1:]
avg_annual_expenditures = df_filtered[df_filtered['Item'] == 'Average annual expenditures'].iloc[0, 1:]

# Calculate the percentage of Food expenditures
percentage_food = (food_expenditure / avg_annual_expenditures)

# Create a DataFrame for visualization
percentage_df = pd.DataFrame({
    'Year': percentage_food.index,
    'Percentage': percentage_food.values
})

# Create the Altair chart
chart = alt.Chart(percentage_df).mark_line().encode(
    x=alt.X('Year:O', axis=alt.Axis(title='Year')),
    y=alt.Y('Percentage:Q', axis=alt.Axis(title='Percentage of Average Annual Expenditures', format='%')),
    tooltip=['Year', alt.Tooltip('Percentage', format='.2f')]
).properties(
    title='Percentage of Food Expenditures over the Years'
).interactive() # Added interactivity for zooming and panning

# Display the chart
chart

alt.Chart(...)